use criterion::{criterion_group, criterion_main};
use gitcomet_ui_gpui::perf_alloc::{PerfTrackingAllocator, TRACKING_MIMALLOC};

#[global_allocator]
static GLOBAL: &PerfTrackingAllocator = &TRACKING_MIMALLOC;

#[path = "performance/mod.rs"]
mod performance_benches;

use performance_benches::*;

criterion_group! {
    name = benches;
    config = performance_benches::benchmark_criterion();
    targets =
        bench_open_repo,
        bench_branch_sidebar,
        bench_branch_sidebar_extreme_scale,
        bench_branch_sidebar_cache,
        bench_history_graph,
        bench_history_cache_build,
        bench_history_cache_build_extreme_scale,
        bench_history_load_more_append,
        bench_history_scope_switch,
        bench_repo_switch,
        bench_commit_details,
        bench_status_list,
        bench_status_multi_select,
        bench_status_select_diff_open,
        bench_merge_open_bootstrap,
        bench_frame_timing,
        bench_keyboard,
        bench_staging,
        bench_undo_redo,
        bench_git_ops,
        bench_large_file_diff_scroll,
        bench_file_diff_replacement_alignment,
        bench_text_input_prepaint_windowed,
        bench_text_input_runs_streamed_highlight,
        bench_text_input_long_line_cap,
        bench_text_input_wrap_incremental_tabs,
        bench_text_input_wrap_incremental_burst_edits,
        bench_text_model_snapshot_clone_cost,
        bench_text_model_bulk_load_large,
        bench_text_model_fragmented_edits,
        bench_file_diff_syntax_prepare,
        bench_file_diff_syntax_query_stress,
        bench_file_diff_syntax_reparse,
        bench_file_diff_inline_syntax_projection,
        bench_file_diff_syntax_cache_drop,
        bench_prepared_syntax_multidoc_cache_hit_rate,
        bench_prepared_syntax_chunk_miss_cost,
        bench_large_html_syntax,
        bench_worktree_preview_render,
        bench_markdown_preview_parse_build,
        bench_markdown_preview_render,
        bench_markdown_preview_scroll,
        bench_diff_open_markdown_preview_first_window,
        bench_diff_open_image_preview_first_paint,
        bench_diff_open_svg_dual_path_first_window,
        bench_conflict_three_way_scroll,
        bench_conflict_three_way_prepared_syntax_scroll,
        bench_conflict_three_way_visible_map_build,
        bench_conflict_two_way_split_scroll,
        bench_conflict_load_duplication,
        bench_conflict_two_way_diff_build,
        bench_conflict_two_way_word_highlights,
        bench_conflict_resolved_output_gutter_scroll,
        bench_conflict_search_query_update,
        bench_patch_diff_search_query_update,
        bench_patch_diff_paged_rows,
        bench_diff_open_patch_first_window,
        bench_diff_open_file_split_first_window,
        bench_diff_open_file_inline_first_window,
        bench_diff_open_patch_deep_window,
        bench_diff_open_patch_100k_lines_first_window,
        bench_diff_open_conflict_compare_first_window,
        bench_diff_refresh_rev_only_same_content,
        bench_conflict_split_resize_step,
        bench_conflict_streamed_provider,
        bench_conflict_streamed_resolved_output,
        bench_pane_resize_drag_step,
        bench_diff_split_resize_drag_step,
        bench_window_resize_layout,
        bench_window_resize_layout_extreme_scale,
        bench_history_column_resize_drag_step,
        bench_repo_tab_drag,
        bench_resolved_output_recompute_incremental,
        bench_scrollbar_drag_step,
        bench_search,
        bench_fs_event,
        bench_network,
        bench_clipboard,
        bench_display,
        bench_real_repo,
}
criterion_main!(benches);
